### ISSUE TITLE
body right padding not properly managed

### ISSUE THREAD

**Issue by ludalex** [sethbrasile/ember-remodal#33]
When I open a remodal and there is a scrollbar because the body content is higher than the viewport, remodal applies `padding-right: 15px` to the `body` style.

If something happens in that remodal that causes the content to shrink thus removing the need of a scrollbar, remodal or ember-remodal doesn't remove the padding from the body when the remodal closes, causing this:

![screen shot 2016-09-13 at 18 47 45](https://cloud.githubusercontent.com/assets/1538479/18482981/9a972ee2-79e2-11e6-8bf8-18dcee3e6f89.png)

**Comment by sethbrasile** [comment]
The remodal library would be to blame for this. @ludalex, you may want to open an issue over there?

This addon is just consuming remodal for the actual modal creation / DOM manipulation.

https://github.com/VodkaBears/Remodal

We could technically "hack" out this bug here, but I'd prefer to attempt to address it in remodal first.

Closing this for now, and we will re-address if the folks over at the remodal repo don't care to fix.

**Comment by ludalex** [comment]
Thanks :) https://github.com/VodkaBears/Remodal/issues/263
